services:
  web:
    build: .
    entrypoint: /app/entrypoint.sh
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - redis
      - rabbitmq

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data

  # redis:
  #   image: redis
    
  
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    # env_file:
    #   - rabbitmq/.env
    environment:
      - RABBITMQ_NODE_IP_ADDRESS=0.0.0.0
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_QUEUE=my_queue
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_USER=myuser
      # - REDIS_PASSWORD=mypassword
    # entrypoint: ./entrypoint.sh