# Generated by Django 5.1.1 on 2024-11-01 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_add_comment', 'can add a comment under this post')]},
        ),
    ]
