# Generated by Django 5.1.1 on 2024-11-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='profile_picture\\profile.png', null=True, upload_to='profile_picture'),
        ),
    ]
