# Generated by Django 5.1.2 on 2024-10-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='defalut_profile.png', null=True, upload_to='profile_picture'),
        ),
    ]
